/**
 * Human labels for the settings editor. Anything not listed here still renders
 * — the key is prettified — so adding a setting never breaks the panel.
 */
export const settingsGroupMeta: Record<string, { title: string; description: string }> = {
  brand: { title: 'Brand', description: 'Nome, descrittore e claim. Compaiono in header, footer e metadati.' },
  contact: { title: 'Contatti', description: 'Numeri, email e messaggio precompilato di WhatsApp.' },
  social: { title: 'Social', description: 'Link ai profili. Lascia vuoto per nascondere il link.' },
  hero: { title: 'Hero della home', description: 'La prima schermata: è quella che decide se l’utente resta.' },
  home: { title: 'Sezioni della home', description: 'Titoli e introduzioni di ogni blocco della home.' },
  about: { title: 'Chi c’è dietro', description: 'La sezione personale. Tienila breve e concreta.' },
  partners: { title: 'Collaboriamo', description: 'Pagina rivolta a location, planner e catering.' },
  requestForm: { title: 'Modulo di richiesta', description: 'Testi del configuratore e del messaggio di conferma.' },
  seo: { title: 'SEO', description: 'Title, meta description e immagine di anteprima predefiniti.' },
  legal: { title: 'Legale', description: 'Titolare del trattamento e testi di privacy e cookie policy.' },
};

export const settingsFieldLabels: Record<string, string> = {
  name: 'Nome',
  descriptor: 'Descrittore',
  claim: 'Claim',
  legalName: 'Ragione sociale',
  vatNumber: 'Partita IVA',
  phone: 'Telefono (formato +39…)',
  whatsapp: 'WhatsApp (solo cifre, es. 39…)',
  whatsappMessage: 'Messaggio precompilato WhatsApp',
  email: 'Email',
  serviceArea: 'Zona servita',
  availability: 'Orari di risposta',
  instagram: 'URL Instagram',
  tiktok: 'URL TikTok',
  facebook: 'URL Facebook',
  eyebrow: 'Sopratitolo',
  title: 'Titolo',
  subtitle: 'Sottotitolo',
  primaryCta: 'Pulsante principale',
  secondaryCta: 'Pulsante secondario',
  imagePath: 'Immagine',
  videoPath: 'Video (facoltativo)',
  badges: 'Punti di rassicurazione (uno per riga)',
  valuePropTitle: 'Titolo — perché noi',
  valuePropIntro: 'Introduzione — perché noi',
  valueProps: 'Punti di forza (Titolo | Testo, uno per riga)',
  howTitle: 'Titolo — come funziona',
  howIntro: 'Introduzione — come funziona',
  steps: 'Passaggi (Titolo | Testo, uno per riga)',
  packagesTitle: 'Titolo — pacchetti',
  packagesIntro: 'Introduzione — pacchetti',
  cocktailsTitle: 'Titolo — cocktail',
  cocktailsIntro: 'Introduzione — cocktail',
  eventsTitle: 'Titolo — eventi',
  eventsIntro: 'Introduzione — eventi',
  galleryTitle: 'Titolo — galleria',
  galleryIntro: 'Introduzione — galleria',
  testimonialsTitle: 'Titolo — recensioni',
  testimonialsIntro: 'Introduzione — recensioni',
  faqTitle: 'Titolo — FAQ',
  faqIntro: 'Introduzione — FAQ',
  finalCtaTitle: 'Titolo — CTA finale',
  finalCtaBody: 'Testo — CTA finale',
  body: 'Testo',
  facts: 'Fatti concreti (uno per riga)',
  signature: 'Firma / nome del titolare',
  intro: 'Introduzione',
  bullets: 'Elenco puntato (uno per riga)',
  ctaLabel: 'Etichetta del pulsante',
  submitLabel: 'Etichetta del pulsante di invio',
  reassurance: 'Testo di rassicurazione',
  successTitle: 'Titolo pagina di conferma',
  successBody: 'Testo pagina di conferma',
  siteName: 'Nome del sito',
  defaultTitle: 'Title predefinito',
  titleTemplate: 'Template dei title (%s = titolo pagina)',
  defaultDescription: 'Meta description predefinita',
  ogImagePath: 'Immagine di anteprima social',
  focusKeywords: 'Parole chiave di riferimento',
  dataController: 'Titolare del trattamento',
  controllerAddress: 'Indirizzo del titolare',
  privacyEmail: 'Email per richieste privacy',
  lastUpdated: 'Data ultimo aggiornamento (AAAA-MM-GG)',
  privacyBody: 'Testo privacy policy (vuoto = testo predefinito)',
  cookieBody: 'Testo cookie policy (vuoto = testo predefinito)',
};

export function labelForSettingsField(key: string): string {
  return settingsFieldLabels[key] ?? key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase());
}

/** Fields that deserve a tall editor rather than a single line. */
export const longFields = new Set([
  'body',
  'privacyBody',
  'cookieBody',
  'subtitle',
  'intro',
  'valuePropIntro',
  'howIntro',
  'packagesIntro',
  'cocktailsIntro',
  'eventsIntro',
  'galleryIntro',
  'testimonialsIntro',
  'faqIntro',
  'finalCtaBody',
  'successBody',
  'reassurance',
  'defaultDescription',
  'whatsappMessage',
  'blurb',
]);
